name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  buttons_tabbar: ^1.3.15
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  chewie: ^1.11.0
  curved_navigation_bar: ^1.0.6
  firebase_core: ^3.12.0
  firebase_messaging: ^15.2.3
  flutter:
    sdk: flutter
  flutter_local_notifications: ^18.0.1
  get: ^4.7.2
  hive: ^2.2.3
  intl: ^0.20.2
  json_annotation: ^4.9.0
  jwt_decoder: ^2.0.1
  shared_preferences: ^2.5.2
  syncfusion_flutter_sliders: ^28.2.9
  video_player: ^2.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.4

flutter:
  uses-material-design: true
  assets: 
    - assets/icons/
